tools:
    exceptions: https://sentry.io/organizations/dcsil/issues/?project=5480347
    logging: ''
    ci: https://github.com/dcsil/sphinx-frontend/blob/main/.github/workflows/node.js.yml
  
services:
    production: https://dashboard.heroku.com/apps/sphinx-tool

docs:
    getting_started: ./README.md

commands:
    bootstrap: chmod 700 script/bootstrap; script/bootstrap
    database: ''
    server: npm run start
    test: npm run test
