export const DATA_UNIT = {
  SourceIP: '',
  DestinationIP: '',
  SourcePort: '',
  DestinationPort: '',
  TimeStamp: '',
  Duration: 'seconds',
  FlowBytesSent: 'bytes',
  FlowSentRate: 'bytes / sec',
  FlowBytesReceived: 'bytes',
  FlowReceivedRate: 'bytes / sec',
  PacketLengthMean: 'bytes / sec',
  PacketTimeMean: 'seconds',
  ResponseTimeTimeMean: 'seconds',
  DoH: '',
  label: '',
};
export const DATA_NAMING = {
  SourceIP: 'Source IP',
  DestinationIP: 'Destination IP',
  SourcePort: 'Source Port',
  DestinationPort: 'Destination Port',
  Duration: 'Duration',
  TimeStamp: 'Time Stamp',
  FlowBytesSent: 'Total Bytes Sent',
  FlowSentRate: 'Flow Sent Rate',
  FlowBytesReceived: 'Total Bytes Received',
  FlowReceivedRate: 'Flow Received Rate',
  PacketLengthMean: 'Avg Packet Length',
  PacketTimeMean: 'Packet Time',
  ResponseTimeTimeMean: 'Avg Response Time',
  DoH: 'DNS over HTTPS',
  label: 'Label',
};
