#!/bin/bash

# Exit if any subcommand fails

set -e

install_homebrew() {
  if [[ "$(uname -s)" = "Darwin" ]]; then
    echo "Installing Homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi
}

install_postgres() {
  if [[ "$(uname -s)" = "Darwin" ]]; then
    brew cask install postgres
  else
    command -v psql > /dev/null 2>&1
    if [ $? -eq 0 ]; then
      echo "postgres already installed"
    else
      sudo apt-get update
      sudo apt install postgresql postgresql-contrib
    fi
  fi
}

install_node() {
  echo "Installing Node"
  if [[ "$(uname -s)" = "Darwin" ]]; then
    brew install node
  else
    sudo apt-get update
    sudo apt-get install nodejs
  fi
}


if [[ "$(uname -s)" = "Darwin" ]]; then
    command -v brew > /dev/null 2>&1
    if [ $? -eq 0 ]; then
        echo "Homebrew already installed"
    else
        install_homebrew # No-ops in Linux
    fi

    command -v node > /dev/null 2>&1
    if [ $? -eq 0 ]; then
        echo "node already installed"
    else
        install_node
    fi
      
else

    install_node

    echo "==> Installing client npm dependencies…"
    npm install
    
fi
